# Generated by Django 3.2.20 on 2023-09-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True)),
                ('category_picture', models.ImageField(null=True, upload_to='static/category/')),
                ('category_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('msg', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=100, null=True)),
                ('qualif', models.CharField(max_length=200, null=True)),
                ('instructor_post', models.CharField(max_length=100, null=True)),
                ('instructor_pic', models.ImageField(null=True, upload_to='static/instpic')),
            ],
        ),
        migrations.CreateModel(
            name='newbatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bpic', models.ImageField(null=True, upload_to='static/batchpic')),
                ('bdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.TextField(null=True)),
                ('slider_description', models.TextField(null=True)),
                ('slider_picture', models.ImageField(null=True, upload_to='static/slider')),
            ],
        ),
        migrations.CreateModel(
            name='studentbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='submittedtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('answer_file', models.FileField(null=True, upload_to='static/submittedtask')),
                ('tid', models.CharField(max_length=20, null=True)),
                ('userid', models.CharField(max_length=200, null=True)),
                ('marks', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('profile', models.ImageField(null=True, upload_to='static/profile')),
                ('course', models.CharField(max_length=30, null=True)),
                ('pyear', models.CharField(max_length=30, null=True)),
                ('college', models.TextField(null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('passwd', models.CharField(max_length=10)),
                ('batchid', models.IntegerField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.studentbatch')),
            ],
        ),
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_picture', models.ImageField(null=True, upload_to='static/placement')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='static/companylogo')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.batch')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.college')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.session_year')),
            ],
        ),
        migrations.CreateModel(
            name='mytask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('task_file', models.FileField(null=True, upload_to='static/task')),
                ('added_date', models.DateField(null=True)),
                ('taskbatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.batch')),
            ],
        ),
        migrations.CreateModel(
            name='mylectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.CharField(max_length=300, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='static/videopic')),
                ('video_description', models.TextField(null=True)),
                ('added_date', models.DateField()),
                ('video_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.studentbatch')),
                ('video_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='enotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('notes_pic', models.ImageField(null=True, upload_to='static/enotes')),
                ('pdf_notes', models.FileField(null=True, upload_to='static/pdf')),
                ('added_date', models.DateField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.studentbatch')),
            ],
        ),
        migrations.CreateModel(
            name='batchtiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clink', models.CharField(max_length=300, null=True)),
                ('timing', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.studentbatch')),
            ],
        ),
    ]
