# Generated by Django 4.2.11 on 2024-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_fsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtiming',
            name='clname',
            field=models.TextField(null=True),
        ),
    ]
